# Generated by Django 5.2.12 on 2026-08-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(db_index=True, max_length=40, unique=True)),
                ('tc_ndc_no', models.CharField(blank=True, max_length=40, verbose_name='T.C. / N.D.C. No.')),
                ('admission_no', models.CharField(blank=True, max_length=40)),
                ('certificate_date', models.DateField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150, verbose_name="Father's / Guardian's Name")),
                ('mother_name', models.CharField(blank=True, max_length=150, verbose_name="Mother's Name")),
                ('nationality', models.CharField(blank=True, max_length=60)),
                ('religion', models.CharField(blank=True, max_length=60)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('branch_level', models.CharField(blank=True, choices=[('JUNIOR', 'Junior'), ('DIPLOMA', 'Diploma'), ('DEGREE', 'Degree'), ('BTECH', 'B.Tech'), ('PG', 'PG Course')], max_length=10)),
                ('date_of_last_exam', models.DateField(blank=True, null=True)),
                ('year_of_passing', models.CharField(blank=True, max_length=20)),
                ('library_cleared', models.BooleanField(default=False)),
                ('library_remarks', models.CharField(blank=True, max_length=150)),
                ('lab_cleared', models.BooleanField(default=False)),
                ('lab_remarks', models.CharField(blank=True, max_length=150)),
                ('sports_cleared', models.BooleanField(default=False)),
                ('sports_remarks', models.CharField(blank=True, max_length=150)),
                ('other_fee_desc', models.CharField(blank=True, max_length=100, verbose_name='Other Fee (specify)')),
                ('other_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('other_fee_cleared', models.BooleanField(default=False)),
                ('other_fee_remarks', models.CharField(blank=True, max_length=150)),
                ('prepared_by', models.CharField(blank=True, max_length=100)),
                ('verified_by', models.CharField(blank=True, max_length=100)),
                ('hod_name', models.CharField(blank=True, max_length=100, verbose_name='HOD')),
                ('os_name', models.CharField(blank=True, max_length=100, verbose_name='O/S (Office Superintendent)')),
                ('accounts_officer_name', models.CharField(blank=True, max_length=100)),
                ('principal_name', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clearance / certificate detail',
                'verbose_name_plural': 'Clearance / certificate details',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=40, unique=True)),
                ('tracking', models.CharField(blank=True, max_length=40)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('order_status', models.CharField(blank=True, max_length=30)),
                ('status_message', models.CharField(blank=True, max_length=255)),
                ('app_code', models.CharField(blank=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('merchant_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('billing_tel', models.CharField(blank=True, max_length=20)),
                ('billing_email', models.CharField(blank=True, max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('id_no', models.CharField(blank=True, max_length=40)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('parent_mobile', models.CharField(blank=True, max_length=20)),
                ('admission_type', models.CharField(blank=True, max_length=30)),
                ('fee_type', models.CharField(blank=True, max_length=60)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('branch', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Group / Branch')),
                ('course', models.CharField(blank=True, db_index=True, max_length=30)),
                ('course_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('year', models.CharField(blank=True, db_index=True, max_length=10)),
                ('roll_no', models.CharField(db_index=True, max_length=40)),
                ('academic_year', models.CharField(blank=True, db_index=True, max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date_installment1', models.DateField(blank=True, null=True)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('current_fees', models.JSONField(blank=True, default=dict)),
                ('past_dues', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
