# Generated by Django 5.2.12 on 2026-08-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearance',
            name='course_branch_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Course / Branch Name'),
        ),
        migrations.AddField(
            model_name='clearance',
            name='roll_no_register',
            field=models.CharField(blank=True, max_length=40, verbose_name='Roll No. / Register No.'),
        ),
        migrations.AddField(
            model_name='clearance',
            name='section_display',
            field=models.CharField(blank=True, max_length=20, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='clearance',
            name='student_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Name of Student'),
        ),
        migrations.AddField(
            model_name='clearance',
            name='year_of_study',
            field=models.CharField(blank=True, max_length=60, verbose_name='Year of Study / Semester'),
        ),
        migrations.CreateModel(
            name='FeePaidRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Semester / Payment')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount Paid (₹)')),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('receipt_no', models.CharField(blank=True, max_length=60, verbose_name='Challan No. / Receipt No.')),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_rows', to='students.clearance')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
