# Generated by Django 5.2.12 on 2026-09-10 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_clearance_course_branch_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearance',
            name='lab_cleared',
        ),
        migrations.RemoveField(
            model_name='clearance',
            name='lab_remarks',
        ),
        migrations.RemoveField(
            model_name='clearance',
            name='library_cleared',
        ),
        migrations.RemoveField(
            model_name='clearance',
            name='library_remarks',
        ),
        migrations.RemoveField(
            model_name='clearance',
            name='sports_cleared',
        ),
        migrations.RemoveField(
            model_name='clearance',
            name='sports_remarks',
        ),
        migrations.CreateModel(
            name='DueApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('LIBRARY', 'Library'), ('LAB', 'Laboratory'), ('SPORTS', 'Sports / Physical Education')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'No Due'), ('DUES', 'Dues')], default='PENDING', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=150)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='students.clearance')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='due_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department'],
                'constraints': [models.UniqueConstraint(fields=('clearance', 'department'), name='unique_department_per_clearance')],
            },
        ),
    ]
