# Generated by Django 5.2.12 on 2026-09-10 09:11

from django.db import migrations

from students.departments import DEPARTMENT_GROUP_NAMES


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for name in DEPARTMENT_GROUP_NAMES:
        Group.objects.get_or_create(name=name)


def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=DEPARTMENT_GROUP_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_clearance_lab_cleared_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]
