# Generated by Django 5.2.12 on 2026-09-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_create_department_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='dueapproval',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount Due (₹)'),
        ),
    ]
