# Generated by Django 5.2.12 on 2026-09-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_dueapproval_amount_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepaidrow',
            name='source_order_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40),
        ),
    ]
