# Generated by Django 5.2.12 on 2026-09-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_backfill_feepaidrow_source_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(blank=True, max_length=40, verbose_name='ID No.')),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('parent_mobile', models.CharField(blank=True, max_length=20)),
                ('admission_type', models.CharField(blank=True, max_length=30)),
                ('fee_type', models.CharField(blank=True, max_length=60)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('branch', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Group / Branch')),
                ('course', models.CharField(blank=True, db_index=True, max_length=30)),
                ('course_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('year', models.CharField(blank=True, db_index=True, max_length=10)),
                ('roll_no', models.CharField(db_index=True, max_length=40)),
                ('academic_year', models.CharField(blank=True, db_index=True, max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date_installment1', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('rtf', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='RTF')),
                ('current_fees', models.JSONField(blank=True, default=dict)),
                ('past_dues', models.JSONField(blank=True, default=dict)),
                ('installment', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('roll_no', 'installment'), name='unique_demand_per_installment')],
            },
        ),
    ]
