"""
Django settings for nodues_tc project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ui5g&nk&5zcfsgkj66450b7-gpe*^mi%y_%s()=ie!j-724_=('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# '.vercel.app' covers the production alias and every per-deployment/preview
# URL Vercel hands out (they all end in .vercel.app unless a custom domain
# is attached). ALLOWED_HOSTS env var lets a custom domain be added later
# without another code change/deploy.
ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = ['https://*.vercel.app']

# Vercel terminates TLS and forwards to the app over plain HTTP — without
# this, Django thinks every request is insecure, which breaks CSRF/session
# cookies on POST requests (e.g. login) even though the site is served
# over HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'students',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nodues_tc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nodues_tc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Vercel's filesystem is read-only at runtime except /tmp — SQLite can't
# open the committed db.sqlite3 for writing at all there (hence
# "attempt to write a readonly database" on login). /tmp is the only
# writable path, so on Vercel we copy the committed db in there once per
# cold start and point SQLite at that copy instead.
#
# This makes writes *possible*, not durable: /tmp is wiped whenever a new
# serverless instance spins up (a new deployment, scaling up, an instance
# recycling), and concurrent requests can land on different instances
# that each have their own /tmp — so two users hitting the site at the
# same time can each write to a different copy of the database. Anything
# written this way should be treated as disposable, not as the real
# system of record.
if os.environ.get('VERCEL'):
    import shutil

    _RUNTIME_DB = Path('/tmp/db.sqlite3')
    if not _RUNTIME_DB.exists():
        shutil.copy(BASE_DIR / 'db.sqlite3', _RUNTIME_DB)
    _DB_PATH = _RUNTIME_DB
else:
    _DB_PATH = BASE_DIR / 'db.sqlite3'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _DB_PATH,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Vercel's serverless build never runs `collectstatic`, so WhiteNoise is
# told to serve straight from STATICFILES_DIRS (via Django's static file
# finders) instead of expecting files under STATIC_ROOT.
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
